- name: Install base packages
  hosts: all
  vars:
    package_list:
       - sudo
       - vim
       - screen
       - zsh
       - bash-completion
       - git
  become: true
  gather_facts: true

  tasks:
    - ping: ~

    - name: Install base packages APT
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ package_list }}"
      when: ( (hostvars[inventory_hostname].ansible_distribution is search('Debian'))
            or ( hostvars[inventory_hostname].ansible_distribution is search('Devuan'))
            or ( hostvars[inventory_hostname].ansible_distribution is search('Ubuntu')) )

    - name: Install base packages APK
      apk:
        name: "{{ item }}"
        state: present
      loop: "{{ package_list }}"
      when: (hostvars[inventory_hostname].ansible_distribution is search('Alpine'))

