- name: Tests
  hosts: all
  become: no

  tasks:
    - ping: ~

    - name: Print username
      debug:
        var:  "{{ username }}"

    - name: Print password
      debug:
        var:  "{{ pass }}"


    - name: Try simple API call
      debug:
        var:  "{{ pass }}"
      delegate_to: localhost



    - name: List all snapshots
      community.proxmox.proxmox_snap_info:
        api_host: "{{ proxmox_host }}"
        api_user: "ansible"
        api_token_id: "{{ username }}"
        api_token_secret: "{{ pass }}"
        validate_certs: false
        hostname: "{{ inventory_hostname }}"
      register: snap_list
      delegate_to: localhost

    - name: Display snapshots
      ansible.builtin.debug:
        var: snap_list
      delegate_to: localhost


