- name: Tests
  hosts: all
  become: no

  tasks:
    - ping: ~

    - name: Print endpoint
      debug:
        var: proxmox_api

    - name: Print username
      debug:
        var:  "{{ username }}"

    - name: Print password
      debug:
        var:  "{{ pass }}"

