- name: Upgrade all packages to the latest version
  hosts: all

  tasks:
    - ping: ~

    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
      when: ( ( hostvars[inventory_hostname].ansible_distribution is search('Debian'))
            or ( hostvars[inventory_hostname].ansible_distribution is search('Devuan')) )

    - name: Upgrade installed packages APT
      become: true
      apt:
        upgrade: dist
      when: ( (hostvars[inventory_hostname].ansible_distribution is search('Debian'))
            or (hostvars[inventory_hostname].ansible_distribution is search('Devuan')) )

    - name: Remove useless packages from the cache
      become: true
      apt:
        autoclean: yes
      when: ( (hostvars[inventory_hostname].ansible_distribution is search('Debian'))
            or (hostvars[inventory_hostname].ansible_distribution is search('Devuan')) )

    - name: Remove dependencies that are no longer required
      become: true
      apt:
        autoremove: yes
      when: ( (hostvars[inventory_hostname].ansible_distribution is search('Debian'))
            or (hostvars[inventory_hostname].ansible_distribution is search('Devuan')) )

    - name: upgrade Alpine
      become: true
      apk: 
        available: yes
        upgrade: yes
        update_cache: yes
      when: (hostvars[inventory_hostname].ansible_distribution is search('Alpine'))
